<?php

return [
    // These values are public and are sent to the browser on every page load.
    'public_env' => [
        'VITE_PROFILE_NAME' => env('VITE_PROFILE_NAME'),
        'VITE_PROFILE_ADDRESS' => env('VITE_PROFILE_ADDRESS'),
        'VITE_PROFILE_IMAGE_URL' => env('VITE_PROFILE_IMAGE_URL'),
        'VITE_PROFILE_YEARS_EXPERIENCE' => env('VITE_PROFILE_YEARS_EXPERIENCE'),
        'VITE_PROFILE_SYSTEMS_PROJECTS' => env('VITE_PROFILE_SYSTEMS_PROJECTS'),
        'VITE_PROFILE_CORE_STACK' => env('VITE_PROFILE_CORE_STACK'),
        'VITE_CONTACT_EMAIL' => env('VITE_CONTACT_EMAIL'),
        'VITE_CONTACT_PHONE' => env('VITE_CONTACT_PHONE'),
        'VITE_CONTACT_INTERESTS' => env('VITE_CONTACT_INTERESTS'),
        'VITE_CONTACT_RESPONSE_NOTE' => env('VITE_CONTACT_RESPONSE_NOTE'),
        'VITE_SOCIAL_GITHUB_URL' => env('VITE_SOCIAL_GITHUB_URL'),
        'VITE_SOCIAL_INSTAGRAM_URL' => env('VITE_SOCIAL_INSTAGRAM_URL'),
        'VITE_SOCIAL_FACEBOOK_URL' => env('VITE_SOCIAL_FACEBOOK_URL'),
        'VITE_FOOTER_BRAND_TITLE' => env('VITE_FOOTER_BRAND_TITLE'),
        'VITE_RESUME_DOWNLOAD_URL' => env('VITE_RESUME_DOWNLOAD_URL'),
    ],
];
